## ЗАДАЧА - Поиск вакансии "Энергетик" с зараплатой минимум 100 000 рублей в регионе "Челябинская область" (код 74)

# 1. Импорт библиотек и ссылок

In [1]:
import requests
import time
import pandas as pd
import numpy as np
from tqdm import tqdm
import os
import csv

In [2]:
link = 'http://opendata.trudvsem.ru/api/v1/vacancies/region/74'
answer = requests.get(link)

# 2. Проверка запроса от сайта

In [3]:
answer.status_code

200

# 3. Просмотр полученного текста

In [4]:
answer.text

'{"status":"200","request":{"api":"v1"},"meta":{"total":12281,"limit":100},"results":{"vacancies":[{"vacancy":{"id":"6f306638-8cb8-11f1-8e8d-9b4c228a975b","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1047422507736","email":"zakupki@npoelm.ru","hr-agency":false,"inn":"7449044990","kpp":"744901001","name":"АО \\"НПО \\"ЭЛЕКТРОМАШИНА\\"","ogrn":"1047422507736","url":"https://trudvsem.ru/company/1047422507736"},"creation-date":"2026-07-31","date_modify":"2026-08-06T13:39:39+0300","salary":"от 68000","salary_min":68000,"salary_max":80000,"job-name":"Литейщик металлов и сплавов","vac_url":"https://trudvsem.ru/vacancy/card/1047422507736/6f306638-8cb8-11f1-8e8d-9b4c228a975b","schedule":"Сменная работа","qualification":"Не требуется","requirements":"Опыт работы на производстве","duty":"Заливка цветного металла из одного или двух крановых ковшей; Подготовка заливочных устройств, изложниц и др. различных устройств заливки; Определение внешних признаков пригодности жидкого металла.","category":{"specialisation":"Производство"},"requirement":{"education":"Среднее профессиональное образование","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1","lng":"61.474634","lat":"55.122714"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 255-22-85"},{"contact_type":"Эл. почта","contact_value":"personal@uvz.npoelm.ru"}],"contact_person":"Засыпалова Мария Владимировна","work_places":2,"code_profession":"101999","typicalPosition":"Литейщик","skills":[],"addressOffice":"101","workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":["По графику сменности"],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"ae4f1c48-8cb7-11f1-b30a-b76653c82188","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1047422507736","email":"zakupki@npoelm.ru","hr-agency":false,"inn":"7449044990","kpp":"744901001","name":"АО \\"НПО \\"ЭЛЕКТРОМАШИНА\\"","ogrn":"1047422507736","url":"https://trudvsem.ru/company/1047422507736"},"creation-date":"2026-07-31","date_modify":"2026-08-06T13:39:11+0300","salary":"от 65000","salary_min":65000,"salary_max":65000,"job-name":"Опиловщик фасонных отливок","vac_url":"https://trudvsem.ru/vacancy/card/1047422507736/ae4f1c48-8cb7-11f1-b30a-b76653c82188","schedule":"Полный рабочий день","qualification":"Не требуется","requirements":"Опыт работы на производстве","duty":"Зачистка деталей Опиловка ЛПС","category":{"specialisation":"Производство"},"requirement":{"education":"Среднее профессиональное образование","experience":0},"addresses":{"address":[{"location":"Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1","lng":"61.474634","lat":"55.122714"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 255-22-85"},{"contact_type":"Эл. почта","contact_value":"personal@uvz.npoelm.ru"}],"contact_person":"Засыпалова Мария Владимировна","work_places":4,"code_profession":"103525","typicalPosition":"Ничего не выбрано","skills":[],"addressOffice":"101","workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"c692e148-7c3d-11f1-be4b-5ffb8b1668a9","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1047422507736","email":"zakupki@npoelm.ru","hr-agency":false,"inn":"7449044990","kpp":"744901001","name":"АО \\"НПО \\"ЭЛЕКТРОМАШИНА\\"","ogrn":"1047422507736","url":"https://trudvsem.ru/company/1047422507736"},"creation-date":"2026-07-10","date_modify":"2026-08-06T13:38:38+0300","salary":"от 106000","salary_min":106000,"salary_max":106000,"job-name":"Мастер контрольный (участка, цеха)","vac_url":"https://trudvsem.ru/vacancy/card/1047422507736/c692e148-7c3d-11f1-be4b-5ffb8b1668a9","schedule":"Полный рабочий день","qualification":"мастер","requirements":"Умение планировать работу персонала; Знать технологию производства; Умение руководить коллективом.","duty":"1. Своевременная подготовка производства, обеспечение комплектующими и деталями заводского производства; 2. Контроль выполнения производственного задания; 3. Контроль соблюдения технологических процессов;","category":{"specialisation":"Производство"},"requirement":{"education":"Высшее образование — специалитет, магистратура","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1","lng":"61.474634","lat":"55.122714"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 255-22-85"},{"contact_type":"Эл. почта","contact_value":"personal@uvz.npoelm.ru"}],"contact_person":"Засыпалова Мария Владимировна","work_places":1,"code_profession":"201934","typicalPosition":"Мастер / Мастер участка / Мастер цеха (не указана предметная область)","skills":[],"addressOffice":"101","workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"f1e30528-80e1-11f1-9f2b-a9dc3ecfdb9f","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1047422507736","email":"zakupki@npoelm.ru","hr-agency":false,"inn":"7449044990","kpp":"744901001","name":"АО \\"НПО \\"ЭЛЕКТРОМАШИНА\\"","ogrn":"1047422507736","url":"https://trudvsem.ru/company/1047422507736"},"creation-date":"2026-07-16","date_modify":"2026-08-06T13:38:10+0300","salary":"от 55000","salary_min":55000,"salary_max":55000,"job-name":"Диспетчер","vac_url":"https://trudvsem.ru/vacancy/card/1047422507736/f1e30528-80e1-11f1-9f2b-a9dc3ecfdb9f","schedule":"Сменная работа","qualification":"ГО ЧС, пожарная безопасность","requirements":"Уверенный пользователь ПК; Опыт работы диспетчером ЕДДС, МЧС, димпетчерских службах.","duty":"1. Сбор обращений от подразделений по сбоям инженерных сетей, поломкам оборудования и связи; 2. Оперативное уведомление технических служб для устранения аварий; 3. Мониторинг статуса заявок и сроков выхода ремонтных бригад на объекты; 4. Запуск систем оповещения персонала, сбор информации о проишествиях и строгое выполнение указаний бюро ГОЧСиПБ; 5. Фиксация производственного травматизма, вызов экстренных служб и немедленное уведомление руководства.","category":{"specialisation":"Производство"},"requirement":{"education":"Среднее профессиональное образование","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1","lng":"61.474634","lat":"55.122714"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 255-22-85"},{"contact_type":"Эл. почта","contact_value":"personal@uvz.npoelm.ru"}],"contact_person":"Засыпалова Мария Владимировна","work_places":3,"code_profession":"200900","typicalPosition":"Диспетчер","skills":[],"addressOffice":"оф.101","workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":["По графику сменности"],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"8cd8a048-80e1-11f1-9d9f-7de008f3dac7","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1047422507736","email":"zakupki@npoelm.ru","hr-agency":false,"inn":"7449044990","kpp":"744901001","name":"АО \\"НПО \\"ЭЛЕКТРОМАШИНА\\"","ogrn":"1047422507736","url":"https://trudvsem.ru/company/1047422507736"},"creation-date":"2026-07-16","date_modify":"2026-08-06T13:37:43+0300","salary":"от 75000","salary_min":75000,"salary_max":80000,"job-name":"Токарь 5 р.","vac_url":"https://trudvsem.ru/vacancy/card/1047422507736/8cd8a048-80e1-11f1-9d9f-7de008f3dac7","employment":"Полная занятость","schedule":"Полный рабочий день","qualification":"токарь","requirements":"Образование среднее профессиональное","duty":"Согласно должностной инструкции","category":{"specialisation":"Производство"},"requirement":{"education":"Среднее профессиональное образование","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1","lng":"61.474634","lat":"55.122714"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 255-22-85"},{"contact_type":"Эл. почта","contact_value":"personal@uvz.npoelm.ru"}],"contact_person":"Мария Владимировна Засыпалова","work_places":2,"code_profession":"105085","typicalPosition":"Токарь","skills":[],"addressOffice":"101","workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"conditions":"Допустимые","trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"2628a1b8-f5b8-11f0-8628-a3cca5294b78","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1157456009810","email":"TEPLOCOM.2015@yandex.ru","hr-agency":false,"inn":"7415091329","kpp":"741501001","name":"МУП \\"ТЕПЛОКОМ\\"","ogrn":"1157456009810","url":"https://trudvsem.ru/company/1157456009810"},"creation-date":"2026-01-20","date_modify":"2026-08-06T13:37:07+0300","salary":"от 31200","salary_min":31200,"salary_max":31200,"job-name":"Слесарь по контрольно-измерительным приборам и автоматике","vac_url":"https://trudvsem.ru/vacancy/card/1157456009810/2628a1b8-f5b8-11f0-8628-a3cca5294b78","employment":"Полная занятость","schedule":"Полный рабочий день","qualification":"нет","requirements":"Ответственность","duty":"Обеспечивать надежную и бесперебойную работу приборов. Производить ремонт","category":{"specialisation":"ЖКХ, эксплуатация"},"requirement":{"education":"Среднее профессиональное образование","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;","lng":"60.389281","lat":"54.97362"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 700-95-80"},{"contact_type":"Эл. почта","contact_value":"teplocom.2015@Yandex.ru"}],"contact_person":"Диваева Ксения Сергеевна","work_places":1,"code_profession":"104685","typicalPosition":"Слесарь КИПиА","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"6e30c428-a503-11f0-b214-efc3bb2eec02","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1157456009810","email":"TEPLOCOM.2015@yandex.ru","hr-agency":false,"inn":"7415091329","kpp":"741501001","name":"МУП \\"ТЕПЛОКОМ\\"","ogrn":"1157456009810","url":"https://trudvsem.ru/company/1157456009810"},"creation-date":"2025-10-09","date_modify":"2026-08-06T13:37:01+0300","salary":"от 45000","salary_min":45000,"salary_max":45000,"job-name":"Мастер участка","vac_url":"https://trudvsem.ru/vacancy/card/1157456009810/6e30c428-a503-11f0-b214-efc3bb2eec02","employment":"Полная занятость","schedule":"Сменная работа","qualification":"нет","requirements":"Дисциплинированность, ответственность","duty":"Осуществляет руководство технической эксплуатацией сетей водопровода.","category":{"specialisation":"ЖКХ, эксплуатация"},"requirement":{"education":"Среднее профессиональное образование","experience":0},"addresses":{"address":[{"location":"Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;","lng":"60.389281","lat":"54.97362"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 700-95-80"},{"contact_type":"Эл. почта","contact_value":"teplocom.2015@Yandex.ru"}],"contact_person":"Диваева Ксения Сергеевна","work_places":1,"code_profession":"202006","typicalPosition":"Мастер / Мастер участка / Мастер цеха (не указана предметная область)","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":["Только дневная смена"],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"f0d8ced8-f5bd-11f0-ba7d-9959eb3311ba","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1157456009810","email":"TEPLOCOM.2015@yandex.ru","hr-agency":false,"inn":"7415091329","kpp":"741501001","name":"МУП \\"ТЕПЛОКОМ\\"","ogrn":"1157456009810","url":"https://trudvsem.ru/company/1157456009810"},"creation-date":"2026-01-20","date_modify":"2026-08-06T13:36:54+0300","salary":"от 40000","salary_min":40000,"salary_max":40000,"job-name":"Электромонтер по ремонту и обслуживанию электрооборудования","vac_url":"https://trudvsem.ru/vacancy/card/1157456009810/f0d8ced8-f5bd-11f0-ba7d-9959eb3311ba","employment":"Полная занятость","schedule":"Полный рабочий день","qualification":"нет","requirements":"ответственность","duty":"Обслуживания электрооборудования","category":{"specialisation":"ЖКХ, эксплуатация"},"requirement":{"education":"Среднее профессиональное образование","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;","lng":"60.389281","lat":"54.97362"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 700-95-80"},{"contact_type":"Эл. почта","contact_value":"teplocom.2015@Yandex.ru"}],"contact_person":"Диваева Ксения Сергеевна","work_places":1,"code_profession":"105534","typicalPosition":"Электромонтажник / Электромонтер","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"1b68d985-06a9-11ee-8437-c915d4ea89c1","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1157456009810","email":"TEPLOCOM.2015@yandex.ru","hr-agency":false,"inn":"7415091329","kpp":"741501001","name":"МУП \\"ТЕПЛОКОМ\\"","ogrn":"1157456009810","url":"https://trudvsem.ru/company/1157456009810"},"creation-date":"2023-06-09","date_modify":"2026-08-06T13:36:47+0300","salary":"от 45000","salary_min":45000,"salary_max":45000,"job-name":"слесарь- сантехник","vac_url":"https://trudvsem.ru/vacancy/card/1157456009810/1b68d985-06a9-11ee-8437-c915d4ea89c1","employment":"Полная занятость","schedule":"Полный рабочий день","qualification":"нет","requirements":"Ответственность","duty":"Слесарные работы","category":{"specialisation":"ЖКХ, эксплуатация"},"requirement":{"education":"Среднее профессиональное образование","experience":0},"addresses":{"address":[{"location":"Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;","lng":"60.389281","lat":"54.97362"}]},"social_protected":"","term":{"text":"MONTHLY 30 %"},"contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 700-95-80"},{"contact_type":"Эл. почта","contact_value":"teplocom.2015@Yandex.ru"}],"contact_person":"Диваева Ксения Сергеевна","work_places":2,"code_profession":"104682","typicalPosition":"Слесарь-сантехник","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"07bb4a48-792d-11f1-bfbc-a1d6d860641d","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1157456009810","email":"TEPLOCOM.2015@yandex.ru","hr-agency":false,"inn":"7415091329","kpp":"741501001","name":"МУП \\"ТЕПЛОКОМ\\"","ogrn":"1157456009810","url":"https://trudvsem.ru/company/1157456009810"},"creation-date":"2026-07-06","date_modify":"2026-08-06T13:36:39+0300","salary":"от 43000","salary_min":43000,"salary_max":43000,"job-name":"Бухгалтер","vac_url":"https://trudvsem.ru/vacancy/card/1157456009810/07bb4a48-792d-11f1-bfbc-a1d6d860641d","schedule":"Полный рабочий день","qualification":"нет","requirements":"Дисциплинированность, ответственность","duty":"согласно должностной инструкции","category":{"specialisation":"ЖКХ, эксплуатация"},"requirement":{"education":"Среднее профессиональное образование","experience":0},"addresses":{"address":[{"location":"Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 700-95-80"},{"contact_type":"Эл. почта","contact_value":"mixail.badaev@yandex.ru"}],"contact_person":"Бадаев Михаил Васильевич","work_places":1,"code_profession":"200202","typicalPosition":"Бухгалтер","skills":[],"workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"616dd1a8-3ef6-11f1-af40-15277f213853","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1047422507736","email":"zakupki@npoelm.ru","hr-agency":false,"inn":"7449044990","kpp":"744901001","name":"АО \\"НПО \\"ЭЛЕКТРОМАШИНА\\"","ogrn":"1047422507736","url":"https://trudvsem.ru/company/1047422507736"},"creation-date":"2026-04-23","date_modify":"2026-08-06T13:36:24+0300","salary":"от 70000","salary_min":70000,"salary_max":70000,"job-name":"Испытатель агрегатов, приборов и чувствительных элементов","vac_url":"https://trudvsem.ru/vacancy/card/1047422507736/616dd1a8-3ef6-11f1-af40-15277f213853","schedule":"Полный рабочий день","qualification":"испытатель деталей и приборов","requirements":"Умение работать с техпроцессами и конструкторской документацией.","duty":"1. Монтаж не сложных схем испытаний и подключение к ним испытываемых изделий; 2. Испытания в динамическом режиме; 3. Определять дефекты испытываемых изделий; 4. Выполнение необходимых расчетов.","category":{"specialisation":"Производство"},"requirement":{"education":"Среднее профессиональное образование","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1","lng":"61.474634","lat":"55.122714"}]},"social_protected":"","contact_list":[{"contact_type":"Телефон","contact_value":"+7(351) 255-22-85"},{"contact_type":"Эл. почта","contact_value":"personal@uvz.npoelm.ru"}],"contact_person":"Засыпалова Мария Владимировна","work_places":1,"code_profession":"101461","typicalPosition":"Ничего не выбрано","skills":[],"addressOffice":"101","workPlaceType":{"workPlaceForeign":false,"workPlaceOrdinary":true,"workPlaceQuota":false,"workPlaceSpecial":false},"shift":[],"trainingDays":0,"currency":"«руб.»"}},{"vacancy":{"id":"52630458-7b5a-11f1-bfbc-a1d6d860641d","source":"Вакансия работодателя","region":{"region_code":"7400000000000","name":"Челябинская область"},"company":{"companycode":"1157456009810","email":"TEPLOCOM.2015@yandex.ru","hr-agency":false,"inn":"7415091329","kpp":"741501001","name":"МУП \\"ТЕПЛОКОМ\\"","ogrn":"1157456009810","url":"https://trudvsem.ru/company/1157456009810"},"creation-date":"2026-07-09","date_modify":"2026-08-06T13:36:22+0300","salary":"от 40000","salary_min":40000,"salary_max":40000,"job-name":"Электромонтер по ремонту и обслуживанию электрооборудования","vac_url":"https://trudvsem.ru/vacancy/card/1157456009810/52630458-7b5a-11f1-bfbc-a1d6d860641d","schedule":"Полный рабочий день","qualification":"нет","requirements":"Дисциплинированность, ответственность","duty":"согласно должностной инструкции","category":{"specialisation":"ЖКХ, эксплуатация"},"requirement":{"education":"Среднее профессиональное образование","experience":1},"addresses":{"address":[{"location":"Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;","lng":"60.389281","lat":"54.97362"}]},"social_protected":"Граждане, уволенные с во

# 4. Получаем JSON

In [5]:
dct_vacs = answer.json()
print(dct_vacs)

{'status': '200', 'request': {'api': 'v1'}, 'meta': {'total': 12281, 'limit': 100}, 'results': {'vacancies': [{'vacancy': {'id': '6f306638-8cb8-11f1-8e8d-9b4c228a975b', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1047422507736', 'email': 'zakupki@npoelm.ru', 'hr-agency': False, 'inn': '7449044990', 'kpp': '744901001', 'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"', 'ogrn': '1047422507736', 'url': 'https://trudvsem.ru/company/1047422507736'}, 'creation-date': '2026-07-31', 'date_modify': '2026-08-06T13:39:39+0300', 'salary': 'от 68000', 'salary_min': 68000, 'salary_max': 80000, 'job-name': 'Литейщик металлов и сплавов', 'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/6f306638-8cb8-11f1-8e8d-9b4c228a975b', 'schedule': 'Сменная работа', 'qualification': 'Не требуется', 'requirements': 'Опыт работы на производстве', 'duty': 'Заливка цветного металла из одного или двух крановых ковшей; Подготовка заливочных устройств, изложниц и др. различных устройств заливки; Определение внешних признаков пригодности жидкого металла.', 'category': {'specialisation': 'Производство'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 1}, 'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1', 'lng': '61.474634', 'lat': '55.122714'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 255-22-85'}, {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}], 'contact_person': 'Засыпалова Мария Владимировна', 'work_places': 2, 'code_profession': '101999', 'typicalPosition': 'Литейщик', 'skills': [], 'addressOffice': '101', 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': ['По графику сменности'], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': 'ae4f1c48-8cb7-11f1-b30a-b76653c82188', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1047422507736', 'email': 'zakupki@npoelm.ru', 'hr-agency': False, 'inn': '7449044990', 'kpp': '744901001', 'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"', 'ogrn': '1047422507736', 'url': 'https://trudvsem.ru/company/1047422507736'}, 'creation-date': '2026-07-31', 'date_modify': '2026-08-06T13:39:11+0300', 'salary': 'от 65000', 'salary_min': 65000, 'salary_max': 65000, 'job-name': 'Опиловщик фасонных отливок', 'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/ae4f1c48-8cb7-11f1-b30a-b76653c82188', 'schedule': 'Полный рабочий день', 'qualification': 'Не требуется', 'requirements': 'Опыт работы на производстве', 'duty': 'Зачистка деталей Опиловка ЛПС', 'category': {'specialisation': 'Производство'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 0}, 'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1', 'lng': '61.474634', 'lat': '55.122714'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 255-22-85'}, {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}], 'contact_person': 'Засыпалова Мария Владимировна', 'work_places': 4, 'code_profession': '103525', 'typicalPosition': 'Ничего не выбрано', 'skills': [], 'addressOffice': '101', 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': 'c692e148-7c3d-11f1-be4b-5ffb8b1668a9', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1047422507736', 'email': 'zakupki@npoelm.ru', 'hr-agency': False, 'inn': '7449044990', 'kpp': '744901001', 'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"', 'ogrn': '1047422507736', 'url': 'https://trudvsem.ru/company/1047422507736'}, 'creation-date': '2026-07-10', 'date_modify': '2026-08-06T13:38:38+0300', 'salary': 'от 106000', 'salary_min': 106000, 'salary_max': 106000, 'job-name': 'Мастер контрольный (участка, цеха)', 'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/c692e148-7c3d-11f1-be4b-5ffb8b1668a9', 'schedule': 'Полный рабочий день', 'qualification': 'мастер', 'requirements': 'Умение планировать работу персонала; Знать технологию производства; Умение руководить коллективом.', 'duty': '1. Своевременная подготовка производства, обеспечение комплектующими и деталями заводского производства; 2. Контроль выполнения производственного задания; 3. Контроль соблюдения технологических процессов;', 'category': {'specialisation': 'Производство'}, 'requirement': {'education': 'Высшее образование — специалитет, магистратура', 'experience': 1}, 'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1', 'lng': '61.474634', 'lat': '55.122714'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 255-22-85'}, {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}], 'contact_person': 'Засыпалова Мария Владимировна', 'work_places': 1, 'code_profession': '201934', 'typicalPosition': 'Мастер / Мастер участка / Мастер цеха (не указана предметная область)', 'skills': [], 'addressOffice': '101', 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': 'f1e30528-80e1-11f1-9f2b-a9dc3ecfdb9f', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1047422507736', 'email': 'zakupki@npoelm.ru', 'hr-agency': False, 'inn': '7449044990', 'kpp': '744901001', 'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"', 'ogrn': '1047422507736', 'url': 'https://trudvsem.ru/company/1047422507736'}, 'creation-date': '2026-07-16', 'date_modify': '2026-08-06T13:38:10+0300', 'salary': 'от 55000', 'salary_min': 55000, 'salary_max': 55000, 'job-name': 'Диспетчер', 'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/f1e30528-80e1-11f1-9f2b-a9dc3ecfdb9f', 'schedule': 'Сменная работа', 'qualification': 'ГО ЧС, пожарная безопасность', 'requirements': 'Уверенный пользователь ПК; Опыт работы диспетчером ЕДДС, МЧС, димпетчерских службах.', 'duty': '1. Сбор обращений от подразделений по сбоям инженерных сетей, поломкам оборудования и связи; 2. Оперативное уведомление технических служб для устранения аварий; 3. Мониторинг статуса заявок и сроков выхода ремонтных бригад на объекты; 4. Запуск систем оповещения персонала, сбор информации о проишествиях и строгое выполнение указаний бюро ГОЧСиПБ; 5. Фиксация производственного травматизма, вызов экстренных служб и немедленное уведомление руководства.', 'category': {'specialisation': 'Производство'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 1}, 'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1', 'lng': '61.474634', 'lat': '55.122714'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 255-22-85'}, {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}], 'contact_person': 'Засыпалова Мария Владимировна', 'work_places': 3, 'code_profession': '200900', 'typicalPosition': 'Диспетчер', 'skills': [], 'addressOffice': 'оф.101', 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': ['По графику сменности'], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': '8cd8a048-80e1-11f1-9d9f-7de008f3dac7', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1047422507736', 'email': 'zakupki@npoelm.ru', 'hr-agency': False, 'inn': '7449044990', 'kpp': '744901001', 'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"', 'ogrn': '1047422507736', 'url': 'https://trudvsem.ru/company/1047422507736'}, 'creation-date': '2026-07-16', 'date_modify': '2026-08-06T13:37:43+0300', 'salary': 'от 75000', 'salary_min': 75000, 'salary_max': 80000, 'job-name': 'Токарь 5 р.', 'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/8cd8a048-80e1-11f1-9d9f-7de008f3dac7', 'employment': 'Полная занятость', 'schedule': 'Полный рабочий день', 'qualification': 'токарь', 'requirements': 'Образование среднее профессиональное', 'duty': 'Согласно должностной инструкции', 'category': {'specialisation': 'Производство'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 1}, 'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1', 'lng': '61.474634', 'lat': '55.122714'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 255-22-85'}, {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}], 'contact_person': 'Мария Владимировна Засыпалова', 'work_places': 2, 'code_profession': '105085', 'typicalPosition': 'Токарь', 'skills': [], 'addressOffice': '101', 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'conditions': 'Допустимые', 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': '2628a1b8-f5b8-11f0-8628-a3cca5294b78', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1157456009810', 'email': 'TEPLOCOM.2015@yandex.ru', 'hr-agency': False, 'inn': '7415091329', 'kpp': '741501001', 'name': 'МУП "ТЕПЛОКОМ"', 'ogrn': '1157456009810', 'url': 'https://trudvsem.ru/company/1157456009810'}, 'creation-date': '2026-01-20', 'date_modify': '2026-08-06T13:37:07+0300', 'salary': 'от 31200', 'salary_min': 31200, 'salary_max': 31200, 'job-name': 'Слесарь по контрольно-измерительным приборам и автоматике', 'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/2628a1b8-f5b8-11f0-8628-a3cca5294b78', 'employment': 'Полная занятость', 'schedule': 'Полный рабочий день', 'qualification': 'нет', 'requirements': 'Ответственность', 'duty': 'Обеспечивать надежную и бесперебойную работу приборов. Производить ремонт', 'category': {'specialisation': 'ЖКХ, эксплуатация'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 1}, 'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;', 'lng': '60.389281', 'lat': '54.97362'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 700-95-80'}, {'contact_type': 'Эл. почта', 'contact_value': 'teplocom.2015@Yandex.ru'}], 'contact_person': 'Диваева Ксения Сергеевна', 'work_places': 1, 'code_profession': '104685', 'typicalPosition': 'Слесарь КИПиА', 'skills': [], 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': '6e30c428-a503-11f0-b214-efc3bb2eec02', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1157456009810', 'email': 'TEPLOCOM.2015@yandex.ru', 'hr-agency': False, 'inn': '7415091329', 'kpp': '741501001', 'name': 'МУП "ТЕПЛОКОМ"', 'ogrn': '1157456009810', 'url': 'https://trudvsem.ru/company/1157456009810'}, 'creation-date': '2025-10-09', 'date_modify': '2026-08-06T13:37:01+0300', 'salary': 'от 45000', 'salary_min': 45000, 'salary_max': 45000, 'job-name': 'Мастер участка', 'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/6e30c428-a503-11f0-b214-efc3bb2eec02', 'employment': 'Полная занятость', 'schedule': 'Сменная работа', 'qualification': 'нет', 'requirements': 'Дисциплинированность, ответственность', 'duty': 'Осуществляет руководство технической эксплуатацией сетей водопровода.', 'category': {'specialisation': 'ЖКХ, эксплуатация'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 0}, 'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;', 'lng': '60.389281', 'lat': '54.97362'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 700-95-80'}, {'contact_type': 'Эл. почта', 'contact_value': 'teplocom.2015@Yandex.ru'}], 'contact_person': 'Диваева Ксения Сергеевна', 'work_places': 1, 'code_profession': '202006', 'typicalPosition': 'Мастер / Мастер участка / Мастер цеха (не указана предметная область)', 'skills': [], 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': ['Только дневная смена'], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': 'f0d8ced8-f5bd-11f0-ba7d-9959eb3311ba', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1157456009810', 'email': 'TEPLOCOM.2015@yandex.ru', 'hr-agency': False, 'inn': '7415091329', 'kpp': '741501001', 'name': 'МУП "ТЕПЛОКОМ"', 'ogrn': '1157456009810', 'url': 'https://trudvsem.ru/company/1157456009810'}, 'creation-date': '2026-01-20', 'date_modify': '2026-08-06T13:36:54+0300', 'salary': 'от 40000', 'salary_min': 40000, 'salary_max': 40000, 'job-name': 'Электромонтер по ремонту и обслуживанию электрооборудования', 'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/f0d8ced8-f5bd-11f0-ba7d-9959eb3311ba', 'employment': 'Полная занятость', 'schedule': 'Полный рабочий день', 'qualification': 'нет', 'requirements': 'ответственность', 'duty': 'Обслуживания электрооборудования', 'category': {'specialisation': 'ЖКХ, эксплуатация'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 1}, 'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;', 'lng': '60.389281', 'lat': '54.97362'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 700-95-80'}, {'contact_type': 'Эл. почта', 'contact_value': 'teplocom.2015@Yandex.ru'}], 'contact_person': 'Диваева Ксения Сергеевна', 'work_places': 1, 'code_profession': '105534', 'typicalPosition': 'Электромонтажник / Электромонтер', 'skills': [], 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': '1b68d985-06a9-11ee-8437-c915d4ea89c1', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1157456009810', 'email': 'TEPLOCOM.2015@yandex.ru', 'hr-agency': False, 'inn': '7415091329', 'kpp': '741501001', 'name': 'МУП "ТЕПЛОКОМ"', 'ogrn': '1157456009810', 'url': 'https://trudvsem.ru/company/1157456009810'}, 'creation-date': '2023-06-09', 'date_modify': '2026-08-06T13:36:47+0300', 'salary': 'от 45000', 'salary_min': 45000, 'salary_max': 45000, 'job-name': 'слесарь- сантехник', 'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/1b68d985-06a9-11ee-8437-c915d4ea89c1', 'employment': 'Полная занятость', 'schedule': 'Полный рабочий день', 'qualification': 'нет', 'requirements': 'Ответственность', 'duty': 'Слесарные работы', 'category': {'specialisation': 'ЖКХ, эксплуатация'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 0}, 'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;', 'lng': '60.389281', 'lat': '54.97362'}]}, 'social_protected': '', 'term': {'text': 'MONTHLY 30 %'}, 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 700-95-80'}, {'contact_type': 'Эл. почта', 'contact_value': 'teplocom.2015@Yandex.ru'}], 'contact_person': 'Диваева Ксения Сергеевна', 'work_places': 2, 'code_profession': '104682', 'typicalPosition': 'Слесарь-сантехник', 'skills': [], 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': '07bb4a48-792d-11f1-bfbc-a1d6d860641d', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1157456009810', 'email': 'TEPLOCOM.2015@yandex.ru', 'hr-agency': False, 'inn': '7415091329', 'kpp': '741501001', 'name': 'МУП "ТЕПЛОКОМ"', 'ogrn': '1157456009810', 'url': 'https://trudvsem.ru/company/1157456009810'}, 'creation-date': '2026-07-06', 'date_modify': '2026-08-06T13:36:39+0300', 'salary': 'от 43000', 'salary_min': 43000, 'salary_max': 43000, 'job-name': 'Бухгалтер', 'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/07bb4a48-792d-11f1-bfbc-a1d6d860641d', 'schedule': 'Полный рабочий день', 'qualification': 'нет', 'requirements': 'Дисциплинированность, ответственность', 'duty': 'согласно должностной инструкции', 'category': {'specialisation': 'ЖКХ, эксплуатация'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 0}, 'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 700-95-80'}, {'contact_type': 'Эл. почта', 'contact_value': 'mixail.badaev@yandex.ru'}], 'contact_person': 'Бадаев Михаил Васильевич', 'work_places': 1, 'code_profession': '200202', 'typicalPosition': 'Бухгалтер', 'skills': [], 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': '616dd1a8-3ef6-11f1-af40-15277f213853', 'source': 'Вакансия работодателя', 'region': {'region_code': '7400000000000', 'name': 'Челябинская область'}, 'company': {'companycode': '1047422507736', 'email': 'zakupki@npoelm.ru', 'hr-agency': False, 'inn': '7449044990', 'kpp': '744901001', 'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"', 'ogrn': '1047422507736', 'url': 'https://trudvsem.ru/company/1047422507736'}, 'creation-date': '2026-04-23', 'date_modify': '2026-08-06T13:36:24+0300', 'salary': 'от 70000', 'salary_min': 70000, 'salary_max': 70000, 'job-name': 'Испытатель агрегатов, приборов и чувствительных элементов', 'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/616dd1a8-3ef6-11f1-af40-15277f213853', 'schedule': 'Полный рабочий день', 'qualification': 'испытатель деталей и приборов', 'requirements': 'Умение работать с техпроцессами и конструкторской документацией.', 'duty': '1. Монтаж не сложных схем испытаний и подключение к ним испытываемых изделий; 2. Испытания в динамическом режиме; 3. Определять дефекты испытываемых изделий; 4. Выполнение необходимых расчетов.', 'category': {'specialisation': 'Производство'}, 'requirement': {'education': 'Среднее профессиональное образование', 'experience': 1}, 'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1', 'lng': '61.474634', 'lat': '55.122714'}]}, 'social_protected': '', 'contact_list': [{'contact_type': 'Телефон', 'contact_value': '+7(351) 255-22-85'}, {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}], 'contact_person': 'Засыпалова Мария Владимировна', 'work_places': 1, 'code_profession': '101461', 'typicalPosition': 'Ничего не выбрано', 'skills': [], 'addressOffice': '101', 'workPlaceType': {'workPlaceForeign': False, 'workPlaceOrdinary': True, 'workPlaceQuota': False, 'workPlaceSpecial': False}, 'shift': [], 'trainingDays': 0, 'currency': '«руб.»'}}, {'vacancy': {'id': '52630458-7b5a-11f1-bfbc-a1d6d860641d', 'sour

# 5. Просмотр ключей словаря

In [6]:
dct_vacs.keys()

dict_keys(['status', 'request', 'meta', 'results'])

# 6. Анализ ключей

In [7]:
for key, value in dct_vacs.items():
    print(f'Ключ----<<{key}>>----')
    print(value)
    print('--' * 10)

Ключ----<<status>>----
200
--------------------
Ключ----<<request>>----
{'api': 'v1'}
--------------------
Ключ----<<meta>>----
{'total': 12281, 'limit': 100}
--------------------
Ключ----<<results>>----

# 7. Анализ типа данных и преобразование к понятному содержимому

In [8]:
dct_vacs.get('results')

{'vacancies': [{'vacancy': {'id': '6f306638-8cb8-11f1-8e8d-9b4c228a975b',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1047422507736',
     'email': 'zakupki@npoelm.ru',
     'hr-agency': False,
     'inn': '7449044990',
     'kpp': '744901001',
     'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"',
     'ogrn': '1047422507736',
     'url': 'https://trudvsem.ru/company/1047422507736'},
    'creation-date': '2026-07-31',
    'date_modify': '2026-08-06T13:39:39+0300',
    'salary': 'от 68000',
    'salary_min': 68000,
    'salary_max': 80000,
    'job-name': 'Литейщик металлов и сплавов',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/6f306638-8cb8-11f1-8e8d-9b4c228a975b',
    'schedule': 'Сменная работа',
    'qualification': 'Не требуется',
    'requirements': 'Опыт работы на производстве',
    'duty': 'Заливка цветного металла из одного или двух крановых ковшей; Подготовка заливочных устройств, изложниц и др. различных устройств заливки; Определение внешних признаков пригодности жидкого металла.',
    'category': {'specialisation': 'Производство'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 1},
    'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1',
       'lng': '61.474634',
       'lat': '55.122714'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 255-22-85'},
     {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}],
    'contact_person': 'Засыпалова Мария Владимировна',
    'work_places': 2,
    'code_profession': '101999',
    'typicalPosition': 'Литейщик',
    'skills': [],
    'addressOffice': '101',
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': ['По графику сменности'],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': 'ae4f1c48-8cb7-11f1-b30a-b76653c82188',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1047422507736',
     'email': 'zakupki@npoelm.ru',
     'hr-agency': False,
     'inn': '7449044990',
     'kpp': '744901001',
     'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"',
     'ogrn': '1047422507736',
     'url': 'https://trudvsem.ru/company/1047422507736'},
    'creation-date': '2026-07-31',
    'date_modify': '2026-08-06T13:39:11+0300',
    'salary': 'от 65000',
    'salary_min': 65000,
    'salary_max': 65000,
    'job-name': 'Опиловщик фасонных отливок',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/ae4f1c48-8cb7-11f1-b30a-b76653c82188',
    'schedule': 'Полный рабочий день',
    'qualification': 'Не требуется',
    'requirements': 'Опыт работы на производстве',
    'duty': 'Зачистка деталей Опиловка ЛПС',
    'category': {'specialisation': 'Производство'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 0},
    'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1',
       'lng': '61.474634',
       'lat': '55.122714'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 255-22-85'},
     {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}],
    'contact_person': 'Засыпалова Мария Владимировна',
    'work_places': 4,
    'code_profession': '103525',
    'typicalPosition': 'Ничего не выбрано',
    'skills': [],
    'addressOffice': '101',
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': [],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': 'c692e148-7c3d-11f1-be4b-5ffb8b1668a9',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1047422507736',
     'email': 'zakupki@npoelm.ru',
     'hr-agency': False,
     'inn': '7449044990',
     'kpp': '744901001',
     'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"',
     'ogrn': '1047422507736',
     'url': 'https://trudvsem.ru/company/1047422507736'},
    'creation-date': '2026-07-10',
    'date_modify': '2026-08-06T13:38:38+0300',
    'salary': 'от 106000',
    'salary_min': 106000,
    'salary_max': 106000,
    'job-name': 'Мастер контрольный (участка, цеха)',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/c692e148-7c3d-11f1-be4b-5ffb8b1668a9',
    'schedule': 'Полный рабочий день',
    'qualification': 'мастер',
    'requirements': 'Умение планировать работу персонала; Знать технологию производства; Умение руководить коллективом.',
    'duty': '1. Своевременная подготовка производства, обеспечение комплектующими и деталями заводского производства; 2. Контроль выполнения производственного задания; 3. Контроль соблюдения технологических процессов;',
    'category': {'specialisation': 'Производство'},
    'requirement': {'education': 'Высшее образование — специалитет, магистратура',
     'experience': 1},
    'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1',
       'lng': '61.474634',
       'lat': '55.122714'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 255-22-85'},
     {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}],
    'contact_person': 'Засыпалова Мария Владимировна',
    'work_places': 1,
    'code_profession': '201934',
    'typicalPosition': 'Мастер / Мастер участка / Мастер цеха (не указана предметная область)',
    'skills': [],
    'addressOffice': '101',
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': [],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': 'f1e30528-80e1-11f1-9f2b-a9dc3ecfdb9f',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1047422507736',
     'email': 'zakupki@npoelm.ru',
     'hr-agency': False,
     'inn': '7449044990',
     'kpp': '744901001',
     'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"',
     'ogrn': '1047422507736',
     'url': 'https://trudvsem.ru/company/1047422507736'},
    'creation-date': '2026-07-16',
    'date_modify': '2026-08-06T13:38:10+0300',
    'salary': 'от 55000',
    'salary_min': 55000,
    'salary_max': 55000,
    'job-name': 'Диспетчер',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/f1e30528-80e1-11f1-9f2b-a9dc3ecfdb9f',
    'schedule': 'Сменная работа',
    'qualification': 'ГО ЧС, пожарная безопасность',
    'requirements': 'Уверенный пользователь ПК; Опыт работы диспетчером ЕДДС, МЧС, димпетчерских службах.',
    'duty': '1. Сбор обращений от подразделений по сбоям инженерных сетей, поломкам оборудования и связи; 2. Оперативное уведомление технических служб для устранения аварий; 3. Мониторинг статуса заявок и сроков выхода ремонтных бригад на объекты; 4. Запуск систем оповещения персонала, сбор информации о проишествиях и строгое выполнение указаний бюро ГОЧСиПБ; 5. Фиксация производственного травматизма, вызов экстренных служб и немедленное уведомление руководства.',
    'category': {'specialisation': 'Производство'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 1},
    'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1',
       'lng': '61.474634',
       'lat': '55.122714'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 255-22-85'},
     {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}],
    'contact_person': 'Засыпалова Мария Владимировна',
    'work_places': 3,
    'code_profession': '200900',
    'typicalPosition': 'Диспетчер',
    'skills': [],
    'addressOffice': 'оф.101',
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': ['По графику сменности'],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': '8cd8a048-80e1-11f1-9d9f-7de008f3dac7',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1047422507736',
     'email': 'zakupki@npoelm.ru',
     'hr-agency': False,
     'inn': '7449044990',
     'kpp': '744901001',
     'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"',
     'ogrn': '1047422507736',
     'url': 'https://trudvsem.ru/company/1047422507736'},
    'creation-date': '2026-07-16',
    'date_modify': '2026-08-06T13:37:43+0300',
    'salary': 'от 75000',
    'salary_min': 75000,
    'salary_max': 80000,
    'job-name': 'Токарь 5 р.',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/8cd8a048-80e1-11f1-9d9f-7de008f3dac7',
    'employment': 'Полная занятость',
    'schedule': 'Полный рабочий день',
    'qualification': 'токарь',
    'requirements': 'Образование среднее профессиональное',
    'duty': 'Согласно должностной инструкции',
    'category': {'specialisation': 'Производство'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 1},
    'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1',
       'lng': '61.474634',
       'lat': '55.122714'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 255-22-85'},
     {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}],
    'contact_person': 'Мария Владимировна Засыпалова',
    'work_places': 2,
    'code_profession': '105085',
    'typicalPosition': 'Токарь',
    'skills': [],
    'addressOffice': '101',
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': [],
    'conditions': 'Допустимые',
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': '2628a1b8-f5b8-11f0-8628-a3cca5294b78',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1157456009810',
     'email': 'TEPLOCOM.2015@yandex.ru',
     'hr-agency': False,
     'inn': '7415091329',
     'kpp': '741501001',
     'name': 'МУП "ТЕПЛОКОМ"',
     'ogrn': '1157456009810',
     'url': 'https://trudvsem.ru/company/1157456009810'},
    'creation-date': '2026-01-20',
    'date_modify': '2026-08-06T13:37:07+0300',
    'salary': 'от 31200',
    'salary_min': 31200,
    'salary_max': 31200,
    'job-name': 'Слесарь по контрольно-измерительным приборам и автоматике',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/2628a1b8-f5b8-11f0-8628-a3cca5294b78',
    'employment': 'Полная занятость',
    'schedule': 'Полный рабочий день',
    'qualification': 'нет',
    'requirements': 'Ответственность',
    'duty': 'Обеспечивать надежную и бесперебойную работу приборов. Производить ремонт',
    'category': {'specialisation': 'ЖКХ, эксплуатация'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 1},
    'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;',
       'lng': '60.389281',
       'lat': '54.97362'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 700-95-80'},
     {'contact_type': 'Эл. почта',
      'contact_value': 'teplocom.2015@Yandex.ru'}],
    'contact_person': 'Диваева Ксения Сергеевна',
    'work_places': 1,
    'code_profession': '104685',
    'typicalPosition': 'Слесарь КИПиА',
    'skills': [],
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': [],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': '6e30c428-a503-11f0-b214-efc3bb2eec02',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1157456009810',
     'email': 'TEPLOCOM.2015@yandex.ru',
     'hr-agency': False,
     'inn': '7415091329',
     'kpp': '741501001',
     'name': 'МУП "ТЕПЛОКОМ"',
     'ogrn': '1157456009810',
     'url': 'https://trudvsem.ru/company/1157456009810'},
    'creation-date': '2025-10-09',
    'date_modify': '2026-08-06T13:37:01+0300',
    'salary': 'от 45000',
    'salary_min': 45000,
    'salary_max': 45000,
    'job-name': 'Мастер участка',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/6e30c428-a503-11f0-b214-efc3bb2eec02',
    'employment': 'Полная занятость',
    'schedule': 'Сменная работа',
    'qualification': 'нет',
    'requirements': 'Дисциплинированность, ответственность',
    'duty': 'Осуществляет руководство технической эксплуатацией сетей водопровода.',
    'category': {'specialisation': 'ЖКХ, эксплуатация'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 0},
    'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;',
       'lng': '60.389281',
       'lat': '54.97362'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 700-95-80'},
     {'contact_type': 'Эл. почта',
      'contact_value': 'teplocom.2015@Yandex.ru'}],
    'contact_person': 'Диваева Ксения Сергеевна',
    'work_places': 1,
    'code_profession': '202006',
    'typicalPosition': 'Мастер / Мастер участка / Мастер цеха (не указана предметная область)',
    'skills': [],
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': ['Только дневная смена'],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': 'f0d8ced8-f5bd-11f0-ba7d-9959eb3311ba',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1157456009810',
     'email': 'TEPLOCOM.2015@yandex.ru',
     'hr-agency': False,
     'inn': '7415091329',
     'kpp': '741501001',
     'name': 'МУП "ТЕПЛОКОМ"',
     'ogrn': '1157456009810',
     'url': 'https://trudvsem.ru/company/1157456009810'},
    'creation-date': '2026-01-20',
    'date_modify': '2026-08-06T13:36:54+0300',
    'salary': 'от 40000',
    'salary_min': 40000,
    'salary_max': 40000,
    'job-name': 'Электромонтер по ремонту и обслуживанию электрооборудования',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/f0d8ced8-f5bd-11f0-ba7d-9959eb3311ba',
    'employment': 'Полная занятость',
    'schedule': 'Полный рабочий день',
    'qualification': 'нет',
    'requirements': 'ответственность',
    'duty': 'Обслуживания электрооборудования',
    'category': {'specialisation': 'ЖКХ, эксплуатация'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 1},
    'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;',
       'lng': '60.389281',
       'lat': '54.97362'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 700-95-80'},
     {'contact_type': 'Эл. почта',
      'contact_value': 'teplocom.2015@Yandex.ru'}],
    'contact_person': 'Диваева Ксения Сергеевна',
    'work_places': 1,
    'code_profession': '105534',
    'typicalPosition': 'Электромонтажник / Электромонтер',
    'skills': [],
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': [],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': '1b68d985-06a9-11ee-8437-c915d4ea89c1',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1157456009810',
     'email': 'TEPLOCOM.2015@yandex.ru',
     'hr-agency': False,
     'inn': '7415091329',
     'kpp': '741501001',
     'name': 'МУП "ТЕПЛОКОМ"',
     'ogrn': '1157456009810',
     'url': 'https://trudvsem.ru/company/1157456009810'},
    'creation-date': '2023-06-09',
    'date_modify': '2026-08-06T13:36:47+0300',
    'salary': 'от 45000',
    'salary_min': 45000,
    'salary_max': 45000,
    'job-name': 'слесарь- сантехник',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/1b68d985-06a9-11ee-8437-c915d4ea89c1',
    'employment': 'Полная занятость',
    'schedule': 'Полный рабочий день',
    'qualification': 'нет',
    'requirements': 'Ответственность',
    'duty': 'Слесарные работы',
    'category': {'specialisation': 'ЖКХ, эксплуатация'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 0},
    'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;',
       'lng': '60.389281',
       'lat': '54.97362'}]},
    'social_protected': '',
    'term': {'text': 'MONTHLY 30 %'},
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 700-95-80'},
     {'contact_type': 'Эл. почта',
      'contact_value': 'teplocom.2015@Yandex.ru'}],
    'contact_person': 'Диваева Ксения Сергеевна',
    'work_places': 2,
    'code_profession': '104682',
    'typicalPosition': 'Слесарь-сантехник',
    'skills': [],
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': [],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': '07bb4a48-792d-11f1-bfbc-a1d6d860641d',
    'source': 'Вакансия работодателя',
    'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
    'company': {'companycode': '1157456009810',
     'email': 'TEPLOCOM.2015@yandex.ru',
     'hr-agency': False,
     'inn': '7415091329',
     'kpp': '741501001',
     'name': 'МУП "ТЕПЛОКОМ"',
     'ogrn': '1157456009810',
     'url': 'https://trudvsem.ru/company/1157456009810'},
    'creation-date': '2026-07-06',
    'date_modify': '2026-08-06T13:36:39+0300',
    'salary': 'от 43000',
    'salary_min': 43000,
    'salary_max': 43000,
    'job-name': 'Бухгалтер',
    'vac_url': 'https://trudvsem.ru/vacancy/card/1157456009810/07bb4a48-792d-11f1-bfbc-a1d6d860641d',
    'schedule': 'Полный рабочий день',
    'qualification': 'нет',
    'requirements': 'Дисциплинированность, ответственность',
    'duty': 'согласно должностной инструкции',
    'category': {'specialisation': 'ЖКХ, эксплуатация'},
    'requirement': {'education': 'Среднее профессиональное образование',
     'experience': 0},
    'addresses': {'address': [{'location': 'Челябинская область, г Чебаркуль, Суворова улица, дом: Д. 19;'}]},
    'social_protected': '',
    'contact_list': [{'contact_type': 'Телефон',
      'contact_value': '+7(351) 700-95-80'},
     {'contact_type': 'Эл. почта',
      'contact_value': 'mixail.badaev@yandex.ru'}],
    'contact_person': 'Бадаев Михаил Васильевич',
    'work_places': 1,
    'code_profession': '200202',
    'typicalPosition': 'Бухгалтер',
    'skills': [],
    'workPlaceType': {'workPlaceForeign': False,
     'workPlaceOrdinary': True,
     'workPlaceQuota': False,
     'workPlaceSpecial': False},
    'shift': [],
    'trainingDays': 0,
    'currency': '«руб.»'}},
  {'vacancy': {'id': '616dd1a8-3ef6-11f1-af40-15277f213853',

# 8. Получается, что название вакансии 'job-name', и зарплата 'salary_min' находятся внутри {'vacancies'} и защиты в список

In [9]:
vacancy_data = dct_vacs['results'].get('vacancies')
type(vacancy_data)

list

In [10]:
vacancy_data[0]

{'vacancy': {'id': '6f306638-8cb8-11f1-8e8d-9b4c228a975b',
  'source': 'Вакансия работодателя',
  'region': {'region_code': '7400000000000', 'name': 'Челябинская область'},
  'company': {'companycode': '1047422507736',
   'email': 'zakupki@npoelm.ru',
   'hr-agency': False,
   'inn': '7449044990',
   'kpp': '744901001',
   'name': 'АО "НПО "ЭЛЕКТРОМАШИНА"',
   'ogrn': '1047422507736',
   'url': 'https://trudvsem.ru/company/1047422507736'},
  'creation-date': '2026-07-31',
  'date_modify': '2026-08-06T13:39:39+0300',
  'salary': 'от 68000',
  'salary_min': 68000,
  'salary_max': 80000,
  'job-name': 'Литейщик металлов и сплавов',
  'vac_url': 'https://trudvsem.ru/vacancy/card/1047422507736/6f306638-8cb8-11f1-8e8d-9b4c228a975b',
  'schedule': 'Сменная работа',
  'qualification': 'Не требуется',
  'requirements': 'Опыт работы на производстве',
  'duty': 'Заливка цветного металла из одного или двух крановых ковшей; Подготовка заливочных устройств, изложниц и др. различных устройств заливки; Определение внешних признаков пригодности жидкого металла.',
  'category': {'specialisation': 'Производство'},
  'requirement': {'education': 'Среднее профессиональное образование',
   'experience': 1},
  'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Машиностроителей улица, дом 21 к.1',
     'lng': '61.474634',
     'lat': '55.122714'}]},
  'social_protected': '',
  'contact_list': [{'contact_type': 'Телефон',
    'contact_value': '+7(351) 255-22-85'},
   {'contact_type': 'Эл. почта', 'contact_value': 'personal@uvz.npoelm.ru'}],
  'contact_person': 'Засыпалова Мария Владимировна',
  'work_places': 2,
  'code_profession': '101999',
  'typicalPosition': 'Литейщик',
  'skills': [],
  'addressOffice': '101',
  'workPlaceType': {'workPlaceForeign': False,
   'workPlaceOrdinary': True,
   'workPlaceQuota': False,
   'workPlaceSpecial': False},
  'shift': ['По графику сменности'],
  'trainingDays': 0,
  'currency': '«руб.»'}}

# 9. Собираем словарь с нужными пунктами для отбора и базовый список

In [11]:
dct_one = {
	'job-name': None,
    'salary': None,
	'salary_min': None,
    'salary_max': None,
    'company': None,
    'addresses': None,
    'vac_url': None}
 
lst_dict = []
vacancy_dict = dct_one.copy()  # создаем один раз копию для переиспользования

# 10. Выполняем обход с помощью цикла for по всем вакансиям

In [12]:
for vacancy_item in vacancy_data:

    # Извлекаем данные из вложенного словаря 'vacancy'
    vac = vacancy_item['vacancy'] 
    
    # Заполняем поля
    vacancy_dict['job-name'] = vac.get('job-name')
    vacancy_dict['salary'] = vac.get('salary')
    vacancy_dict['salary_min'] = vac.get('salary_min')
    vacancy_dict['salary_max'] = vac.get('salary_max')
    vacancy_dict['company'] = vac.get('company')
    vacancy_dict['addresses'] = vac.get('addresses')
    vacancy_dict['vac_url'] = vac.get('vac_url')
    
    # Добавляем заполненный словарь в список
    lst_dict.append(vacancy_dict.copy())

# 11. Проверяем как собрался список

In [13]:
print(lst_dict[17])

{'job-name': 'Уборщик производственных и служебных помещений', 'salary': 'от 31200', 'salary_min': 31200, 'salary_max': 35000, 'company': {'companycode': '1027403895518', 'email': 'shkola-i4@yandex.ru', 'hr-agency': False, 'inn': '7453045482', 'kpp': '745301001', 'name': 'МБОУ "ШКОЛА-ИНТЕРНАТ № 4 Г. ЧЕЛЯБИНСКА"', 'ogrn': '1027403895518', 'url': 'https://trudvsem.ru/company/1027403895518'}, 'addresses': {'address': [{'location': 'Челябинская область, г Челябинск, Худякова улица, дом: 22;', 'lng': '61.358392', 'lat': '55.148097'}]}, 'vac_url': 'https://trudvsem.ru/vacancy/card/1027403895518/a3e74678-f5ee-11f0-a027-0dd543315e5a'}

# 12. Назначем DataFrame для наглядности

In [14]:
df = pd.DataFrame(lst_dict)
print(df.head())

                             job-name     salary  salary_min  salary_max  \
0         Литейщик металлов и сплавов   от 68000       68000       80000
1          Опиловщик фасонных отливок   от 65000       65000       65000
2  Мастер контрольный (участка, цеха)  от 106000      106000      106000
3                           Диспетчер   от 55000       55000       55000
4                         Токарь 5 р.   от 75000       75000       80000

                                             company  \
0  {'companycode': '1047422507736', 'email': 'zak...
1  {'companycode': '1047422507736', 'email': 'zak...
2  {'companycode': '1047422507736', 'email': 'zak...
3  {'companycode': '1047422507736', 'email': 'zak...
4  {'companycode': '1047422507736', 'email': 'zak...

                                           addresses  \
0  {'address': [{'location': 'Челябинская область...
1  {'address': [{'location': 'Челябинская область...
2  {'address': [{'location': 'Челябинская область...
3  {'address': [{'location': 'Челябинская область...
4  {'address': [{'location': 'Челябинская область...

                                             vac_url
0  https://trudvsem.ru/vacancy/card/1047422507736...
1  https://trudvsem.ru/vacancy/card/1047422507736...
2  https://trudvsem.ru/vacancy/card/1047422507736...
3  https://trudvsem.ru/vacancy/card/1047422507736...
4  https://trudvsem.ru/vacancy/card/1047422507736...

### Не видно нормального названия компании и адреса, переписал цикл for

In [15]:
dct_one = {
    'job-name': None,
    'salary': None,
    'salary_min': None,
    'salary_max': None,
    'company_name': None,      # ← сразу строка, а не словарь
    'address_location': None,  # ← сразу строка, а не словарь
    'vac_url': None
}

lst_dict = []

for vacancy_item in vacancy_data:
    vacancy_dict = dct_one.copy()
    vac = vacancy_item['vacancy']
    
    # Простые поля
    vacancy_dict['job-name'] = vac.get('job-name')
    vacancy_dict['salary'] = vac.get('salary', 0)
    vacancy_dict['salary_min'] = vac.get('salary_min', 0)
    vacancy_dict['salary_max'] = vac.get('salary_max', 0)
    vacancy_dict['vac_url'] = vac.get('vac_url', None)
    
    # Извлекаем название компании
    company = vac.get('company')
    vacancy_dict['company_name'] = company.get('name') if company else None
    
    # Извлекаем адрес
    addresses = vac.get('addresses')
    if addresses and addresses.get('address'):
        vacancy_dict['address_location'] = addresses['address'][0].get('location')
    else:
        vacancy_dict['address_location'] = None
    
    lst_dict.append(vacancy_dict)

In [16]:
# Создаем DataFrame сразу с чистыми данными
df = pd.DataFrame(lst_dict)
df.head()

,job-name,salary,salary_min,salary_max,company_name,address_location,vac_url
0,Литейщик металлов и сплавов,от 68000,68000,80000,"АО ""НПО ""ЭЛЕКТРОМАШИНА""","Челябинская область, г Челябинск, Машиностроит...",https://trudvsem.ru/vacancy/card/1047422507736...
1,Опиловщик фасонных отливок,от 65000,65000,65000,"АО ""НПО ""ЭЛЕКТРОМАШИНА""","Челябинская область, г Челябинск, Машиностроит...",https://trudvsem.ru/vacancy/card/1047422507736...
2,"Мастер контрольный (участка, цеха)",от 106000,106000,106000,"АО ""НПО ""ЭЛЕКТРОМАШИНА""","Челябинская область, г Челябинск, Машиностроит...",https://trudvsem.ru/vacancy/card/1047422507736...
3,Диспетчер,от 55000,55000,55000,"АО ""НПО ""ЭЛЕКТРОМАШИНА""","Челябинская область, г Челябинск, Машиностроит...",https://trudvsem.ru/vacancy/card/1047422507736...
4,Токарь 5 р.,от 75000,75000,80000,"АО ""НПО ""ЭЛЕКТРОМАШИНА""","Челябинская область, г Челябинск, Машиностроит...",https://trudvsem.ru/vacancy/card/1047422507736...

# 13. С применением пагинации (по всем вакансиям в регионе)

In [17]:
offset_number = 0
region_code = 74

dct_one = {
	'job-name': None,
    'salary': None,
	'salary_min': None,
    'salary_max': None,
    'company': None,
    'addresses': None,
    'vac_url': None}
 
lst_dict = []

for offset_number in tqdm(range (0,123)):
    link_pag = f'http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset={offset_number}'
    answer = requests.get(link_pag)
    time.sleep(5)
    print(link_pag)
    if answer.status_code == 200:
        dct_vacs = answer.json()
        dct_vacs.get('results')
        vacancy_data = dct_vacs['results'].get('vacancies')
        for vacancy_item in vacancy_data:
            vacancy_dict = dct_one.copy()
            vac = vacancy_item['vacancy']
            
            # Простые поля
            vacancy_dict['job-name'] = vac.get('job-name')
            vacancy_dict['salary'] = vac.get('salary', 0)
            vacancy_dict['salary_min'] = vac.get('salary_min', 0)
            vacancy_dict['salary_max'] = vac.get('salary_max', 0)
            vacancy_dict['vac_url'] = vac.get('vac_url', None)
            
            # Извлекаем название компании
            company = vac.get('company')
            vacancy_dict['company_name'] = company.get('name') if company else None
            
            # Извлекаем адрес
            addresses = vac.get('addresses')
            if addresses and addresses.get('address'):
                vacancy_dict['address_location'] = addresses['address'][0].get('location')
            else:
                vacancy_dict['address_location'] = None
            
            lst_dict.append(vacancy_dict)

  1%|▋                                                                                 | 1/123 [00:12<26:08, 12.86s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=0

  2%|█▎                                                                                | 2/123 [00:27<27:46, 13.77s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=1

  2%|██                                                                                | 3/123 [00:42<28:41, 14.35s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=2

  3%|██▋                                                                               | 4/123 [00:55<27:18, 13.77s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=3

  4%|███▎                                                                              | 5/123 [01:09<27:08, 13.80s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=4

  5%|████                                                                              | 6/123 [01:22<26:59, 13.84s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=5

  6%|████▋                                                                             | 7/123 [01:37<27:16, 14.11s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=6

  7%|█████▎                                                                            | 8/123 [01:51<27:01, 14.10s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=7

  7%|██████                                                                            | 9/123 [02:06<27:04, 14.25s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=8

  8%|██████▌                                                                          | 10/123 [02:20<26:32, 14.09s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=9

  9%|███████▏                                                                         | 11/123 [02:35<26:55, 14.43s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=10

 10%|███████▉                                                                         | 12/123 [02:49<26:49, 14.50s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=11

 11%|████████▌                                                                        | 13/123 [03:02<25:38, 13.98s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=12

 11%|█████████▏                                                                       | 14/123 [03:17<25:40, 14.13s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=13

 12%|█████████▉                                                                       | 15/123 [03:31<25:45, 14.31s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=14

 13%|██████████▌                                                                      | 16/123 [03:46<25:40, 14.40s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=15

 14%|███████████▏                                                                     | 17/123 [04:01<25:51, 14.64s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=16

 15%|███████████▊                                                                     | 18/123 [04:15<25:23, 14.51s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=17

 15%|████████████▌                                                                    | 19/123 [04:28<24:17, 14.01s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=18

 16%|█████████████▏                                                                   | 20/123 [04:45<25:29, 14.85s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=19

 17%|█████████████▊                                                                   | 21/123 [05:00<25:03, 14.74s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=20

 18%|██████████████▍                                                                  | 22/123 [05:14<24:37, 14.63s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=21

 19%|███████████████▏                                                                 | 23/123 [05:28<24:13, 14.54s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=22

 20%|███████████████▊                                                                 | 24/123 [05:44<24:41, 14.97s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=23

 20%|████████████████▍                                                                | 25/123 [05:57<23:14, 14.23s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=24

 21%|█████████████████                                                                | 26/123 [06:11<22:59, 14.23s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=25

 22%|█████████████████▊                                                               | 27/123 [06:26<23:13, 14.52s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=26

 23%|██████████████████▍                                                              | 28/123 [06:42<23:45, 15.00s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=27

 24%|███████████████████                                                              | 29/123 [06:57<23:34, 15.04s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=28

 24%|███████████████████▊                                                             | 30/123 [07:10<22:15, 14.36s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=29

 25%|████████████████████▍                                                            | 31/123 [07:24<21:48, 14.22s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=30

 26%|█████████████████████                                                            | 32/123 [07:39<21:47, 14.37s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=31

 27%|█████████████████████▋                                                           | 33/123 [07:54<21:46, 14.52s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=32

 28%|██████████████████████▍                                                          | 34/123 [08:08<21:18, 14.36s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=33

 28%|███████████████████████                                                          | 35/123 [08:22<20:59, 14.31s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=34

 29%|███████████████████████▋                                                         | 36/123 [08:36<20:47, 14.34s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=35

 30%|████████████████████████▎                                                        | 37/123 [08:53<21:32, 15.03s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=36

 31%|█████████████████████████                                                        | 38/123 [09:08<21:31, 15.20s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=37

 32%|█████████████████████████▋                                                       | 39/123 [09:22<20:39, 14.76s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=38

 33%|██████████████████████████▎                                                      | 40/123 [09:36<20:07, 14.55s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=39

 33%|███████████████████████████                                                      | 41/123 [09:51<19:51, 14.53s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=40

 34%|███████████████████████████▋                                                     | 42/123 [10:06<20:04, 14.87s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=41

 35%|████████████████████████████▎                                                    | 43/123 [10:22<20:02, 15.04s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=42

 36%|████████████████████████████▉                                                    | 44/123 [10:37<19:39, 14.94s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=43

 37%|█████████████████████████████▋                                                   | 45/123 [10:51<19:16, 14.83s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=44

 37%|██████████████████████████████▎                                                  | 46/123 [11:06<19:09, 14.92s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=45

 38%|██████████████████████████████▉                                                  | 47/123 [11:21<18:45, 14.81s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=46

 39%|███████████████████████████████▌                                                 | 48/123 [11:35<18:21, 14.69s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=47

 40%|████████████████████████████████▎                                                | 49/123 [11:46<16:51, 13.67s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=48

 41%|████████████████████████████████▉                                                | 50/123 [12:00<16:30, 13.57s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=49

 41%|█████████████████████████████████▌                                               | 51/123 [12:15<16:43, 13.94s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=50

 42%|██████████████████████████████████▏                                              | 52/123 [12:29<16:44, 14.15s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=51

 43%|██████████████████████████████████▉                                              | 53/123 [12:44<16:53, 14.47s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=52

 44%|███████████████████████████████████▌                                             | 54/123 [12:58<16:13, 14.10s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=53

 45%|████████████████████████████████████▏                                            | 55/123 [13:12<15:53, 14.03s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=54

 46%|████████████████████████████████████▉                                            | 56/123 [13:25<15:29, 13.87s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=55

 46%|█████████████████████████████████████▌                                           | 57/123 [13:37<14:34, 13.25s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=56

 47%|██████████████████████████████████████▏                                          | 58/123 [13:51<14:31, 13.40s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=57

 48%|██████████████████████████████████████▊                                          | 59/123 [14:06<14:47, 13.87s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=58

 49%|███████████████████████████████████████▌                                         | 60/123 [14:19<14:20, 13.65s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=59

 50%|████████████████████████████████████████▏                                        | 61/123 [14:34<14:28, 14.00s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=60

 50%|████████████████████████████████████████▊                                        | 62/123 [14:49<14:37, 14.39s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=61

 51%|█████████████████████████████████████████▍                                       | 63/123 [15:05<14:46, 14.78s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=62

 52%|██████████████████████████████████████████▏                                      | 64/123 [15:18<14:12, 14.45s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=63

 53%|██████████████████████████████████████████▊                                      | 65/123 [15:32<13:51, 14.33s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=64

 54%|███████████████████████████████████████████▍                                     | 66/123 [15:45<13:01, 13.71s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=65

 54%|████████████████████████████████████████████                                     | 67/123 [15:58<12:49, 13.74s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=66

 55%|████████████████████████████████████████████▊                                    | 68/123 [16:12<12:34, 13.72s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=67

 56%|█████████████████████████████████████████████▍                                   | 69/123 [16:26<12:29, 13.87s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=68

 57%|██████████████████████████████████████████████                                   | 70/123 [16:41<12:35, 14.25s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=69

 58%|██████████████████████████████████████████████▊                                  | 71/123 [16:55<12:15, 14.14s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=70

 59%|███████████████████████████████████████████████▍                                 | 72/123 [17:08<11:35, 13.65s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=71

 59%|████████████████████████████████████████████████                                 | 73/123 [17:22<11:24, 13.69s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=72

 60%|████████████████████████████████████████████████▋                                | 74/123 [17:35<11:04, 13.56s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=73

 61%|█████████████████████████████████████████████████▍                               | 75/123 [17:49<10:54, 13.63s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=74

 62%|██████████████████████████████████████████████████                               | 76/123 [18:01<10:16, 13.13s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=75

 63%|██████████████████████████████████████████████████▋                              | 77/123 [18:15<10:19, 13.48s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=76

 63%|███████████████████████████████████████████████████▎                             | 78/123 [18:29<10:11, 13.58s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=77

 64%|████████████████████████████████████████████████████                             | 79/123 [18:44<10:19, 14.07s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=78

 65%|████████████████████████████████████████████████████▋                            | 80/123 [18:58<10:06, 14.10s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=79

 66%|█████████████████████████████████████████████████████▎                           | 81/123 [19:13<10:04, 14.39s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=80

 67%|██████████████████████████████████████████████████████                           | 82/123 [19:27<09:48, 14.35s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=81

 67%|██████████████████████████████████████████████████████▋                          | 83/123 [19:41<09:29, 14.23s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=82

 68%|███████████████████████████████████████████████████████▎                         | 84/123 [19:55<09:07, 14.04s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=83

 69%|███████████████████████████████████████████████████████▉                         | 85/123 [20:09<08:52, 14.01s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=84

 70%|████████████████████████████████████████████████████████▋                        | 86/123 [20:25<08:57, 14.54s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=85

 71%|█████████████████████████████████████████████████████████▎                       | 87/123 [20:40<08:52, 14.78s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=86

 72%|█████████████████████████████████████████████████████████▉                       | 88/123 [20:54<08:34, 14.69s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=87

 72%|██████████████████████████████████████████████████████████▌                      | 89/123 [21:09<08:14, 14.54s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=88

 73%|███████████████████████████████████████████████████████████▎                     | 90/123 [21:23<07:56, 14.44s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=89

 74%|███████████████████████████████████████████████████████████▉                     | 91/123 [21:35<07:23, 13.87s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=90

 75%|████████████████████████████████████████████████████████████▌                    | 92/123 [21:50<07:17, 14.10s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=91

 76%|█████████████████████████████████████████████████████████████▏                   | 93/123 [22:02<06:43, 13.45s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=92

 76%|█████████████████████████████████████████████████████████████▉                   | 94/123 [22:17<06:44, 13.95s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=93

 77%|██████████████████████████████████████████████████████████████▌                  | 95/123 [22:31<06:29, 13.91s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=94

 78%|███████████████████████████████████████████████████████████████▏                 | 96/123 [22:46<06:28, 14.40s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=95

 79%|███████████████████████████████████████████████████████████████▉                 | 97/123 [23:02<06:23, 14.74s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=96

 80%|████████████████████████████████████████████████████████████████▌                | 98/123 [23:16<06:04, 14.59s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=97

 80%|█████████████████████████████████████████████████████████████████▏               | 99/123 [23:30<05:42, 14.28s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=98

 81%|█████████████████████████████████████████████████████████████████               | 100/123 [23:45<05:35, 14.58s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=99

 82%|█████████████████████████████████████████████████████████████████▋              | 101/123 [23:57<05:01, 13.71s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=100

 83%|██████████████████████████████████████████████████████████████████▎             | 102/123 [24:06<04:18, 12.30s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=101

 84%|██████████████████████████████████████████████████████████████████▉             | 103/123 [24:14<03:41, 11.09s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=102

 85%|███████████████████████████████████████████████████████████████████▋            | 104/123 [24:24<03:22, 10.65s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=103

 85%|████████████████████████████████████████████████████████████████████▎           | 105/123 [24:34<03:10, 10.61s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=104

 86%|████████████████████████████████████████████████████████████████████▉           | 106/123 [24:46<03:06, 10.96s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=105

 87%|█████████████████████████████████████████████████████████████████████▌          | 107/123 [24:56<02:53, 10.83s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=106

 88%|██████████████████████████████████████████████████████████████████████▏         | 108/123 [25:08<02:44, 10.95s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=107

 89%|██████████████████████████████████████████████████████████████████████▉         | 109/123 [25:18<02:31, 10.84s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=108

 89%|███████████████████████████████████████████████████████████████████████▌        | 110/123 [25:27<02:12, 10.22s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=109

 90%|████████████████████████████████████████████████████████████████████████▏       | 111/123 [25:38<02:04, 10.39s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=110

 91%|████████████████████████████████████████████████████████████████████████▊       | 112/123 [25:48<01:54, 10.44s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=111

 92%|█████████████████████████████████████████████████████████████████████████▍      | 113/123 [25:59<01:46, 10.61s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=112

 93%|██████████████████████████████████████████████████████████████████████████▏     | 114/123 [26:10<01:36, 10.73s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=113

 93%|██████████████████████████████████████████████████████████████████████████▊     | 115/123 [26:21<01:25, 10.68s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=114

 94%|███████████████████████████████████████████████████████████████████████████▍    | 116/123 [26:32<01:15, 10.72s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=115

 95%|████████████████████████████████████████████████████████████████████████████    | 117/123 [26:43<01:05, 10.95s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=116

 96%|████████████████████████████████████████████████████████████████████████████▋   | 118/123 [26:55<00:55, 11.15s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=117

 97%|█████████████████████████████████████████████████████████████████████████████▍  | 119/123 [27:05<00:43, 10.98s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=118

 98%|██████████████████████████████████████████████████████████████████████████████  | 120/123 [27:16<00:32, 10.95s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=119

 98%|██████████████████████████████████████████████████████████████████████████████▋ | 121/123 [27:29<00:23, 11.52s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=120

 99%|███████████████████████████████████████████████████████████████████████████████▎| 122/123 [27:40<00:11, 11.43s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=121

100%|████████████████████████████████████████████████████████████████████████████████| 123/123 [27:51<00:00, 13.59s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=122

In [ ]:
offset_number = 0
region_code = 74

# ===== В dct_one ДОЛЖНЫ БЫТЬ ВСЕ ПОЛЯ, КОТОРЫЕ МЫ ИСПОЛЬЗУЕМ =====
dct_one = {
    'job-name': None,
    'salary': None,
    'salary_min': None,
    'salary_max': None,
    'company_name': None,
    'address_location': None,
    'vac_url': None
}
 
lst_dict = []

# ===== ИМПОРТ CSV =====
import csv

# ===== ОТКРЫВАЕМ ФАЙЛ ДЛЯ ЗАПИСИ =====
try:
    with open('vacancies.csv', 'w', newline='', encoding='utf-8') as file:
        columns = ['job-name', 'salary', 'salary_min', 'salary_max', 
                   'company_name', 'address_location', 'vac_url']
        writer = csv.DictWriter(file, fieldnames=columns)
        writer.writeheader()
        file.flush()  # Сразу записываем заголовки на диск
        print('Файл vacancies.csv создан, заголовки записаны')
        
        for offset_number in tqdm(range(0, 123)):
            try:
                link_pag = f'http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset={offset_number}'
                answer = requests.get(link_pag, timeout=30)
                time.sleep(5)
                print(link_pag)
                
                if answer.status_code == 200:
                    dct_vacs = answer.json()
                    vacancy_data = dct_vacs.get('results', {}).get('vacancies', [])
                    
                    for vacancy_item in vacancy_data:
                        try:
                            vacancy_dict = dct_one.copy()
                            vac = vacancy_item.get('vacancy', {})
                            
                            # Простые поля
                            vacancy_dict['job-name'] = vac.get('job-name')
                            vacancy_dict['salary'] = vac.get('salary', 0)
                            vacancy_dict['salary_min'] = vac.get('salary_min', 0)
                            vacancy_dict['salary_max'] = vac.get('salary_max', 0)
                            vacancy_dict['vac_url'] = vac.get('vac_url', None)
                            
                            # Извлекаем название компании
                            company = vac.get('company')
                            vacancy_dict['company_name'] = company.get('name') if company else None
                            
                            # Извлекаем адрес
                            addresses = vac.get('addresses')
                            if addresses and addresses.get('address'):
                                vacancy_dict['address_location'] = addresses['address'][0].get('location')
                            else:
                                vacancy_dict['address_location'] = None
                            
                            # ===== ФИЛЬТРАЦИЯ ПО СЛОВУ "энергетик" =====
                            job_name = vacancy_dict['job-name'] or ''
                            if 'энергетик' in job_name.lower():
                                lst_dict.append(vacancy_dict)
                                
                                if len(lst_dict) >= 100:
                                    writer.writerows(lst_dict)
                                    file.flush()  # ПРИНУДИТЕЛЬНО ЗАПИСЫВАЕМ НА ДИСК
                                    print(f'✅ Сохранено 100 вакансий с "энергетик" (всего в файле: пока не считано)')
                                    lst_dict.clear()
                        
                        except Exception as e:
                            print(f'⚠️ Ошибка при обработке вакансии: {e}')
                            continue
                
                else:
                    print(f'❌ Ошибка запроса: статус {answer.status_code} для {link_pag}')
            
            except requests.exceptions.RequestException as e:
                print(f'🌐 Ошибка сети при запросе {link_pag}: {e}')
                continue
            
            except Exception as e:
                print(f'💥 Неожиданная ошибка при обработке страницы {offset_number}: {e}')
                # Сохраняем то, что уже напарсили
                if lst_dict:
                    writer.writerows(lst_dict)
                    file.flush()  # ПРИНУДИТЕЛЬНО ЗАПИСЫВАЕМ НА ДИСК
                    print(f'💾 Сохранено {len(lst_dict)} вакансий перед ошибкой')
                    lst_dict.clear()
                continue
        
        # ===== СОХРАНЯЕМ ОСТАВШИЕСЯ ВАКАНСИИ =====
        if lst_dict:
            writer.writerows(lst_dict)
            file.flush()  # ПРИНУДИТЕЛЬНО ЗАПИСЫВАЕМ НА ДИСК
            print(f'💾 Сохранено последние {len(lst_dict)} вакансий с "энергетик"')
            lst_dict.clear()
        
        print(f'📁 Файл сохранен: vacancies.csv')
        print(f'📊 Размер файла: {os.path.getsize("vacancies.csv") / 1024:.2f} КБ')

except Exception as e:
    print(f'🔥 КРИТИЧЕСКАЯ ОШИБКА: {e}')
    # Пытаемся сохранить то, что успели напарсить
    try:
        if lst_dict:
            with open('vacancies_backup.csv', 'w', newline='', encoding='utf-8') as backup_file:
                backup_writer = csv.DictWriter(backup_file, fieldnames=columns)
                backup_writer.writeheader()
                backup_writer.writerows(lst_dict)
            print(f'💾 Сохранено {len(lst_dict)} вакансий в backup файл vacancies_backup.csv')
    except:
        print('❌ Не удалось сохранить backup')

print('🏁 Сбор данных завершен!')

Файл vacancies.csv создан, заголовки записаны

  1%|▋                                                                                 | 1/123 [00:14<29:24, 14.47s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=0

  2%|█▎                                                                                | 2/123 [00:29<29:29, 14.63s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=1

  2%|██                                                                                | 3/123 [00:42<28:10, 14.09s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=2

  3%|██▋                                                                               | 4/123 [00:57<28:24, 14.32s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=3

  4%|███▎                                                                              | 5/123 [01:12<28:59, 14.74s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=4

  5%|████                                                                              | 6/123 [01:27<28:54, 14.82s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=5

  6%|████▋                                                                             | 7/123 [01:44<29:58, 15.51s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=6

  7%|█████▎                                                                            | 8/123 [01:59<29:31, 15.40s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=7

  7%|██████                                                                            | 9/123 [02:14<28:58, 15.25s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=8

  8%|██████▌                                                                          | 10/123 [02:30<28:52, 15.33s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=9

  9%|███████▏                                                                         | 11/123 [02:46<29:08, 15.62s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=10

 10%|███████▉                                                                         | 12/123 [03:03<29:33, 15.98s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=11

 11%|████████▌                                                                        | 13/123 [03:18<28:54, 15.77s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=12

 11%|█████████▏                                                                       | 14/123 [03:36<29:41, 16.35s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=13

 12%|█████████▉                                                                       | 15/123 [03:54<30:14, 16.80s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=14

 13%|██████████▌                                                                      | 16/123 [04:10<29:52, 16.75s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=15

 14%|███████████▏                                                                     | 17/123 [04:27<29:36, 16.76s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=16

 15%|███████████▊                                                                     | 18/123 [04:45<29:58, 17.12s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=17

 15%|████████████▌                                                                    | 19/123 [05:02<29:42, 17.14s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=18

 16%|█████████████▏                                                                   | 20/123 [05:18<28:47, 16.77s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=19

 17%|█████████████▊                                                                   | 21/123 [05:35<28:22, 16.69s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=20

 18%|██████████████▍                                                                  | 22/123 [05:50<27:22, 16.27s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=21

 19%|███████████████▏                                                                 | 23/123 [06:06<27:08, 16.28s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=22

 20%|███████████████▊                                                                 | 24/123 [06:23<27:13, 16.50s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=23

 20%|████████████████▍                                                                | 25/123 [06:38<25:58, 15.90s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=24

 21%|█████████████████                                                                | 26/123 [06:55<26:06, 16.15s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=25

 22%|█████████████████▊                                                               | 27/123 [07:09<25:06, 15.69s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=26

 23%|██████████████████▍                                                              | 28/123 [07:26<25:29, 16.10s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=27

 24%|███████████████████                                                              | 29/123 [07:43<25:19, 16.17s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=28

 24%|███████████████████▊                                                             | 30/123 [07:57<24:11, 15.61s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=29

 25%|████████████████████▍                                                            | 31/123 [08:14<24:29, 15.97s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=30

 26%|█████████████████████                                                            | 32/123 [08:30<24:28, 16.13s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=31

 27%|█████████████████████▋                                                           | 33/123 [08:46<24:08, 16.10s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=32

 28%|██████████████████████▍                                                          | 34/123 [09:01<23:30, 15.85s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=33

 28%|███████████████████████                                                          | 35/123 [09:17<22:55, 15.63s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=34

 29%|███████████████████████▋                                                         | 36/123 [09:33<22:50, 15.75s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=35

 30%|████████████████████████▎                                                        | 37/123 [09:49<22:59, 16.04s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=36

 31%|█████████████████████████                                                        | 38/123 [10:05<22:43, 16.05s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=37

 32%|█████████████████████████▋                                                       | 39/123 [10:22<22:44, 16.25s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=38

 33%|██████████████████████████▎                                                      | 40/123 [10:38<22:27, 16.24s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=39

 33%|███████████████████████████                                                      | 41/123 [10:53<21:26, 15.69s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=40

 34%|███████████████████████████▋                                                     | 42/123 [11:06<20:09, 14.93s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=41

 35%|████████████████████████████▎                                                    | 43/123 [11:22<20:22, 15.28s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=42

 36%|████████████████████████████▉                                                    | 44/123 [11:37<19:51, 15.09s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=43

 37%|█████████████████████████████▋                                                   | 45/123 [11:51<19:24, 14.93s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=44

 37%|██████████████████████████████▎                                                  | 46/123 [12:05<18:50, 14.68s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=45

 38%|██████████████████████████████▉                                                  | 47/123 [12:20<18:41, 14.76s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=46

 39%|███████████████████████████████▌                                                 | 48/123 [12:36<18:44, 15.00s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=47

 40%|████████████████████████████████▎                                                | 49/123 [12:51<18:37, 15.09s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=48

 41%|████████████████████████████████▉                                                | 50/123 [13:08<18:58, 15.60s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=49

 41%|█████████████████████████████████▌                                               | 51/123 [13:25<19:08, 15.96s/it]

http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset=50

# 14. Проверка сохранения данных в списке

In [20]:
print(lst_dict[123])

{'job-name': 'Специалист по охране труда', 'salary': 'от 40000', 'salary_min': 40000, 'salary_max': 40000, 'company': None, 'addresses': None, 'vac_url': 'https://trudvsem.ru/vacancy/card/1027401993585/978b0628-1e00-11f1-9ac8-d164183f71d4', 'company_name': 'ГБУЗ "ОСПНБ № 2"', 'address_location': 'Челябинская область, Чебаркульский район, Мирный поселок, Парковая улица, 12а'}

# 15. Сохранение данных из списка в csv (только 3652 получились с читаемым названием, остальные с непонятным текстом)

In [31]:
# Сохранение в CSV файл
name_file = 'вакансии_74_регион.csv'

if lst_dict:
    fieldnames = list(lst_dict[0].keys())
    
    # Используем utf-8-sig для совместимости с Excel
    if os.path.isfile(name_file):
        with open(name_file, 'a', newline='', encoding='utf-8-sig') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter=';', quotechar='"', quoting=csv.QUOTE_ALL)
            writer.writerows(lst_dict)
    else:
        with open(name_file, 'w', newline='', encoding='utf-8-sig') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter=';', quotechar='"', quoting=csv.QUOTE_ALL)
            writer.writeheader()
            writer.writerows(lst_dict)
    
    print(f"Данные сохранены в файл: {name_file}")
    print(f"Всего записей: {len(lst_dict)}")
else:
    print("Нет данных для сохранения")

Данные сохранены в файл: вакансии_74_регион.csv
Всего записей: 10000

# 16. Второй вариант (Парсинг дает только 10000 вакансий, потом идет защита и сервер выдает код 500) Пришлось прибегнуть к помощи ИИ, а также ввести паузу и разбить парсинг на 2 этапа

In [2]:
region_code = 74

dct_one = {
    'job-name': None,
    'salary': None,
    'salary_min': None,
    'salary_max': None,
    'company': None,
    'addresses': None,
    'vac_url': None
}

def clean_text(text):
    """Очистка текста от проблемных символов"""
    if text is None:
        return ''
    if not isinstance(text, str):
        text = str(text)
    return text.strip()

def parse_vacancies(start_offset, end_offset, limit=100):
    """Парсинг вакансий с заданного диапазона offset"""
    lst_dict = []
    
    for offset_number in tqdm(range(start_offset, end_offset), desc=f"Парсинг offset {start_offset}-{end_offset-1}"):
        link_pag = f'http://opendata.trudvsem.ru/api/v1/vacancies/region/74?offset={offset_number}'
        
        try:
            answer = requests.get(link_pag, timeout=30)
            time.sleep(3)  # Задержка между запросами
            
            if answer.status_code == 200:
                dct_vacs = answer.json()
                vacancy_data = dct_vacs.get('results', {}).get('vacancies', [])
                
                for vacancy_item in vacancy_data:
                    vacancy_dict = dct_one.copy()
                    vac = vacancy_item.get('vacancy', {})
                    
                    # Простые поля
                    vacancy_dict['job-name'] = clean_text(vac.get('job-name'))
                    vacancy_dict['salary'] = clean_text(vac.get('salary'))
                    vacancy_dict['salary_min'] = clean_text(vac.get('salary_min'))
                    vacancy_dict['salary_max'] = clean_text(vac.get('salary_max'))
                    vacancy_dict['vac_url'] = clean_text(vac.get('vac_url'))
                    
                    # Извлекаем название компании
                    company = vac.get('company')
                    vacancy_dict['company_name'] = clean_text(company.get('name')) if company else ''
                    
                    # Извлекаем адрес
                    addresses = vac.get('addresses')
                    if addresses and addresses.get('address'):
                        vacancy_dict['address_location'] = clean_text(addresses['address'][0].get('location'))
                    else:
                        vacancy_dict['address_location'] = ''
                    
                    lst_dict.append(vacancy_dict)
            else:
                print(f"Ошибка {answer.status_code} на offset {offset_number}")
                
        except Exception as e:
            print(f"Ошибка при загрузке offset {offset_number}: {e}")
            continue
    
    return lst_dict

def save_to_csv(data, filename, first_write=True):
    """Сохранение данных в CSV"""
    if not data:
        print(f"Нет данных для сохранения в {filename}")
        return
    
    fieldnames = list(data[0].keys())
    mode = 'w' if first_write else 'a'
    
    with open(filename, mode, newline='', encoding='utf-8-sig') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter=';', quotechar='"', quoting=csv.QUOTE_ALL)
        if first_write:
            writer.writeheader()
        writer.writerows(data)
    
    print(f"Сохранено {len(data)} записей в {filename}")

# ============================================
# ГЛАВНАЯ ПРОГРАММА - ПАРСИНГ В ДВА ЭТАПА
# ============================================

# Имена файлов
file_part1 = 'вакансии_74_регион_part1.csv'
file_part2 = 'вакансии_74_регион_part2.csv'
file_total = 'вакансии_74_регион_total.csv'

# Удаляем старые файлы, если существуют
for file in [file_part1, file_part2, file_total]:
    if os.path.isfile(file):
        os.remove(file)
        print(f"Старый файл {file} удален")

print("=== НАЧАЛО ПАРСИНГА ===")

# ЭТАП 1: Парсинг offset с 0 по 60 (первые 61 страница)
print("\n--- ЭТАП 1: offset 0-60 ---")
data_part1 = parse_vacancies(0, 61)
save_to_csv(data_part1, file_part1, first_write=True)

# Пауза между этапами для восстановления сервера
print("\nПауза 300 секунд перед вторым этапом...")
time.sleep(300)

# ЭТАП 2: Парсинг offset с 61 по 122 (оставшиеся 62 страницы)
print("\n--- ЭТАП 2: offset 61-122 ---")
data_part2 = parse_vacancies(61, 123)
save_to_csv(data_part2, file_part2, first_write=True)

# ============================================
# ОБЪЕДИНЕНИЕ ДАННЫХ В ИТОГОВЫЙ ФАЙЛ
# ============================================
print("\n--- ОБЪЕДИНЕНИЕ ДАННЫХ ---")
combined_data = data_part1 + data_part2
save_to_csv(combined_data, file_total, first_write=True)

# ============================================
# ИТОГИ
# ============================================
print("\n=== ПАРСИНГ ЗАВЕРШЕН ===")
print(f"Часть 1: {len(data_part1)} записей -> {file_part1}")
print(f"Часть 2: {len(data_part2)} записей -> {file_part2}")
print(f"Всего: {len(data_part1) + len(data_part2)} записей -> {file_total}")
print(f"\nСозданы файлы:")
print(f"  - {file_part1}")
print(f"  - {file_part2}")
print(f"  - {file_total} (объединенный)")

# Проверяем содержимое файлов
for file in [file_part1, file_part2, file_total]:
    if os.path.isfile(file):
        with open(file, 'r', encoding='utf-8-sig') as f:
            lines = f.readlines()
            print(f"\n{file}: {len(lines) - 1} записей (всего строк: {len(lines)})")

=== НАЧАЛО ПАРСИНГА ===

--- ЭТАП 1: offset 0-60 ---

Парсинг offset 0-60: 100%|█████████████████████████████████████████████████████████████| 61/61 [10:42<00:00, 10.53s/it]

Сохранено 6100 записей в вакансии_74_регион_part1.csv

Пауза 300 секунд перед вторым этапом...

--- ЭТАП 2: offset 61-122 ---

Парсинг offset 61-122:  65%|██████████████████████████████████████                     | 40/62 [06:23<03:11,  8.72s/it]

Ошибка 500 на offset 100

Парсинг offset 61-122:  66%|███████████████████████████████████████                    | 41/62 [06:30<02:54,  8.29s/it]

Ошибка 500 на offset 101

Парсинг offset 61-122:  68%|███████████████████████████████████████▉                   | 42/62 [06:38<02:40,  8.04s/it]

Ошибка 500 на offset 102

Парсинг offset 61-122:  69%|████████████████████████████████████████▉                  | 43/62 [06:46<02:30,  7.93s/it]

Ошибка 500 на offset 103

Парсинг offset 61-122:  71%|█████████████████████████████████████████▊                 | 44/62 [06:51<02:07,  7.10s/it]

Ошибка 500 на offset 104

Парсинг offset 61-122:  73%|██████████████████████████████████████████▊                | 45/62 [06:56<01:51,  6.58s/it]

Ошибка 500 на offset 105

Парсинг offset 61-122:  74%|███████████████████████████████████████████▊               | 46/62 [07:01<01:38,  6.18s/it]

Ошибка 500 на offset 106

Парсинг offset 61-122:  76%|████████████████████████████████████████████▋              | 47/62 [07:08<01:33,  6.24s/it]

Ошибка 500 на offset 107

Парсинг offset 61-122:  77%|█████████████████████████████████████████████▋             | 48/62 [07:14<01:28,  6.32s/it]

Ошибка 500 на offset 108

Парсинг offset 61-122:  79%|██████████████████████████████████████████████▋            | 49/62 [07:21<01:24,  6.48s/it]

Ошибка 500 на offset 109

Парсинг offset 61-122:  81%|███████████████████████████████████████████████▌           | 50/62 [07:28<01:20,  6.72s/it]

Ошибка 500 на offset 110

Парсинг offset 61-122:  82%|████████████████████████████████████████████████▌          | 51/62 [07:36<01:15,  6.86s/it]

Ошибка 500 на offset 111

Парсинг offset 61-122:  84%|█████████████████████████████████████████████████▍         | 52/62 [07:43<01:09,  6.98s/it]

Ошибка 500 на offset 112

Парсинг offset 61-122:  85%|██████████████████████████████████████████████████▍        | 53/62 [07:49<01:01,  6.88s/it]

Ошибка 500 на offset 113

Парсинг offset 61-122:  87%|███████████████████████████████████████████████████▍       | 54/62 [07:56<00:55,  6.90s/it]

Ошибка 500 на offset 114

Парсинг offset 61-122:  89%|████████████████████████████████████████████████████▎      | 55/62 [08:04<00:49,  7.04s/it]

Ошибка 500 на offset 115

Парсинг offset 61-122:  90%|█████████████████████████████████████████████████████▎     | 56/62 [08:12<00:44,  7.45s/it]

Ошибка 500 на offset 116

Парсинг offset 61-122:  92%|██████████████████████████████████████████████████████▏    | 57/62 [08:22<00:40,  8.04s/it]

Ошибка 500 на offset 117

Парсинг offset 61-122:  94%|███████████████████████████████████████████████████████▏   | 58/62 [08:28<00:30,  7.63s/it]

Ошибка 500 на offset 118

Парсинг offset 61-122:  95%|████████████████████████████████████████████████████████▏  | 59/62 [08:37<00:24,  8.08s/it]

Ошибка 500 на offset 119

Парсинг offset 61-122:  97%|█████████████████████████████████████████████████████████  | 60/62 [08:45<00:15,  7.90s/it]

Ошибка 500 на offset 120

Парсинг offset 61-122:  98%|██████████████████████████████████████████████████████████ | 61/62 [08:52<00:07,  7.73s/it]

Ошибка 500 на offset 121

Парсинг offset 61-122: 100%|███████████████████████████████████████████████████████████| 62/62 [08:58<00:00,  8.69s/it]

Ошибка 500 на offset 122
Сохранено 3900 записей в вакансии_74_регион_part2.csv

--- ОБЪЕДИНЕНИЕ ДАННЫХ ---

Сохранено 10000 записей в вакансии_74_регион_total.csv

=== ПАРСИНГ ЗАВЕРШЕН ===
Часть 1: 6100 записей -> вакансии_74_регион_part1.csv
Часть 2: 3900 записей -> вакансии_74_регион_part2.csv
Всего: 10000 записей -> вакансии_74_регион_total.csv

Созданы файлы:
  - вакансии_74_регион_part1.csv
  - вакансии_74_регион_part2.csv
  - вакансии_74_регион_total.csv (объединенный)

вакансии_74_регион_part1.csv: 6100 записей (всего строк: 6101)

вакансии_74_регион_part2.csv: 3900 записей (всего строк: 3901)

вакансии_74_регион_total.csv: 10000 записей (всего строк: 10001)

# После offset=99 нет ответа от сервера, как решить не знаю, буду работать с тем, что насобирал, скорее всего лимит

# 17. Собираем DataFrame для наглядности (в csv лишние колонки влезли, исключил их)

In [11]:
df = pd.read_csv('C:/Users/D/вакансии_74_регион_total.csv',
                 sep=';',
                 encoding='utf-8',
                 quotechar='"',
                 doublequote=True)  # обрабатывать двойные кавычки
df.head()

,job-name,salary,salary_min,salary_max,company,addresses,vac_url,company_name,address_location
0,инженер технолог,от 40000,40000,40000,NaN,NaN,https://trudvsem.ru/vacancy/card/1027402320494...,"ПАО ""ТЕПЛАНТ ВОСТОК""","Челябинская область, г Челябинск, Валдайская у..."
1,Программист,от 50000,50000,50000,NaN,NaN,https://trudvsem.ru/vacancy/card/1027402320494...,"ПАО ""ТЕПЛАНТ ВОСТОК""","Челябинская область, г Челябинск, Валдайская у..."
2,Инженер-конструктор,от 40000,40000,45000,NaN,NaN,https://trudvsem.ru/vacancy/card/1027402320494...,"ПАО ""ТЕПЛАНТ ВОСТОК""","Челябинская область, г Челябинск, Валдайская у..."
3,Лаборант физико-химических исследований,от 40000,40000,46000,NaN,NaN,https://trudvsem.ru/vacancy/card/1187456001480...,"ОГКУ ""ЮУЦДИИ""","Челябинская область, г Челябинск, Профинтерна ..."
4,Педагог-психолог,от 31157,31157,31157,NaN,NaN,https://trudvsem.ru/vacancy/card/1027401029589...,"МБОУ ""ШКОЛА № 15"" С. ДЕМАРИНО","Челябинская область, Пластовский район, Демари..."

# 18. Ввожу фильтр по названию вакансии энергетик и зарплате 100000

In [13]:
flt = (df['salary_min'] >= 100000) & (df['job-name'].str.contains(r'\bэнергетик\b', case=False, na=False))
df[flt]

,job-name,salary,salary_min,salary_max,company,addresses,vac_url,company_name,address_location
857,Энергетик цеха,от 117866,117866,117866,NaN,NaN,https://trudvsem.ru/vacancy/card/5117401000404...,"ООО ""КЛЗ""","Челябинская область, Катав-Ивановский район, г..."

# ИТОГ - всего одна вакансия, ужас, как низко нас ценят.